// components/Footer.jsx
"use client";
import { useState } from 'react';

export default function Footer() {
  const [showMail, setShowMail] = useState(false);
  const year = new Date().getFullYear();

  return (
    <footer className="border-t border-gray-200">
      <div className="py-8 text-sm text-gray-600">
        <p>
          <strong className="font-semibold text-gray-900">Jon Waldstein</strong> by{' '}
          <a className="text-teal-600 hover:text-teal-700" href="https://github.com/jonwaldstein" target="_blank" rel="noreferrer">Jon Waldstein</a>.
        </p>
        <p className="mt-1">{year} Copyright, whatever.</p>
        <div className="mt-4 flex items-center gap-6">
          <a className="hover:text-gray-900" href="#" onClick={(e) => { e.preventDefault(); setShowMail(!showMail); }}>
            Email
          </a>
          <a className="hover:text-gray-900" href="http://linkedin.com/in/jon-waldstein" target="_blank" rel="noreferrer">
            LinkedIn
          </a>
          <a className="hover:text-gray-900" href="https://github.com/jonwaldstein" target="_blank" rel="noreferrer">
            GitHub
          </a>
        </div>
        {showMail && (
          <p className="mt-6 font-semibold text-gray-900">jpwaldstein@gmail.com</p>
        )}
      </div>
    </footer>
  );
}

// components/Footer.vue
<template lang="html">
  <footer class="site-footer">
    <div class="content">
      <p>
        <strong>Jon Waldstein</strong> by <a href="https://github.com/jpwaldstein">Jon Waldstein</a>.
      </p>
      <p>{{date}} Copyright, whatever.</p>
      <div class="contact-links">
    	   <a href="#" v-on:click.prevent="mail = !mail"><i class="far fa-envelope fa-2x"></i></a>
         <a href="http://linkedin.com/in/jon-waldstein" target="_blank"><i class="fab fab fa-linkedin fa-2x"></i></a>
         <a href="https://github.com/jonwaldstein" target="_blank"><i class="fab fa-github fa-2x"></i></a>
      </div>
      <transition name="fade">
        <p class="has-text-weight-semibold" style="margin-top: 25px;" v-show="mail">jpwaldstein@gmail.com</p>
      </transition>
    </div>
  </footer>
</template>

<script>
export default {
  data(){
    return{
        date: new Date().getFullYear(),
        mail: false
    }
  }
}
</script>

<style lang="css">
.site-footer{
  border-top: 4px solid gainsboro;
  margin-top: 50px;
  padding-top: 25px;
  padding-bottom: 25px;
}
</style>
