// components/Intro.vue
<template lang="html">
  <div>
    <h1 class="subtitle">
      Jon Waldstein
    </h1>
    <h2 class="title" style="margin-bottom: 25px;">
      Web development ex·tra·or·di·naire
    </h2>
    <h3 class="is-size-4" style="margin-bottom: 25px;">Below are some examples of my work:</h3>
  </div>
</template>

// components/Intro.jsx
export default function Intro() {
  return (
    <div>
      <h1 className="text-3xl font-light tracking-wide text-gray-800 pb-4">Jon Waldstein</h1>
      <h2 className="text-2xl font-normal tracking-wide mb-6">Web development ex·tra·or·di·naire</h2>
      <h3 className="text-lg mb-6 text-gray-700">Below are some examples of my work:</h3>
    </div>
  );
}
